### ISSUE TITLE
Error in the log

### ISSUE THREAD

**Issue by pmalecek** [Jezza34000/homeassistant_weback_component#44]
Yesterday, this error started appearing in the log (or I noticed it for the first time), and the vacuum cleaner is not available within HA (offline). But it is normally online in the WeBack app.

Logger: homeassistant.util.loop
Zdroj: util/loop.py:77
První výskyt: 06:42:34 (1 výskyt)
Naposledy logováno: 06:42:34

> Detected blocking call to import_module with args ('custom_components.weback_vacuum.vacuum',) in /usr/src/homeassistant/homeassistant/loader.py, line 1307: return importlib.import_module(f"{self.pkg_path}.{platform_name}") inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 229, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 215, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 289, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.13/asyncio/base_events.py", line 712, in run_until_complete self.run_forever() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 683, in run_forever self._run_once() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2050, in _run_once handle._run() File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 160, in _async_component_platform_discovered await self.async_setup_platform(platform, {}, info) File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 251, in async_setup_platform platform = await async_prepare_setup_platform( File "/usr/src/homeassistant/homeassistant/setup.py", line 547, in async_prepare_setup_platform platform = await integration.async_get_platform(domain) File "/usr/src/homeassistant/homeassistant/loader.py", line 1111, in async_get_platform platforms = await self.async_get_platforms((platform_name,)) File "/usr/src/homeassistant/homeassistant/loader.py", line 1176, in async_get_platforms platforms.update(self._load_platforms(platform_names)) File "/usr/src/homeassistant/homeassistant/loader.py", line 1101, in _load_platforms platform_name: self._load_platform(platform_name) File "/usr/src/homeassistant/homeassistant/loader.py", line 1275, in _load_platform cache[full_name] = self._import_platform(platform_name) File "/usr/src/homeassistant/homeassistant/loader.py", line 1307, in _import_platform return importlib.import_module(f"{self.pkg_path}.{platform_name}")

**Comment by nightstorm2** [comment]
I received the same error message after updating to 2026.02:

2026-02-05 08:33:33.075 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to import_module with args ('custom_components.weback_vacuum.vacuum',) in /usr/src/homeassistant/homeassistant/loader.py, line 1307: return importlib.import_module(f"{self.pkg_path}.{platform_name}") inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue
2026-02-05 08:33:33.078 ERROR (MainThread) [homeassistant.setup] Unable to prepare setup for platform 'weback_vacuum.vacuum': Platform not found (cannot import name 'STATE_CLEANING' from 'homeassistant.components.vacuum' (/usr/src/homeassistant/homeassistant/components/vacuum/__init__.py)).

**Comment by carleoneman** [comment]
I'm verifying the same problem, after upgraded to version 2026.2.0


Registo: homeassistant.setup
Origem: setup.py:506
Primeira ocorrência: 01:23:08 (1 ocorrência)
Último registo: 01:23:08

Unable to prepare setup for platform 'weback_vacuum.vacuum': Platform not found (cannot import name 'STATE_CLEANING' from 'homeassistant.components.vacuum' (/usr/src/homeassistant/homeassistant/components/vacuum/__init__.py)).


###################################################################################################


Registo: homeassistant.util.loop
Origem: util/loop.py:77
Primeira ocorrência: 01:23:08 (1 ocorrência)
Último registo: 01:23:08

Detected blocking call to import_module with args ('custom_components.weback_vacuum.vacuum',) in /usr/src/homeassistant/homeassistant/loader.py, line 1307: return importlib.import_module(f"{self.pkg_path}.{platform_name}") inside the event loop; This is causing stability issues. Please create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 229, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 215, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 289, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.13/asyncio/base_events.py", line 712, in run_until_complete self.run_forever() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 683, in run_forever self._run_once() File "/usr/local/lib/python3.13/asyncio/base_events.py", line 2050, in _run_once handle._run() File "/usr/local/lib/python3.13/asyncio/events.py", line 89, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 160, in _async_component_platform_discovered await self.async_setup_platform(platform, {}, info) File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 251, in async_setup_platform platform = await async_prepare_setup_platform( File "/usr/src/homeassistant/homeassistant/setup.py", line 547, in async_prepare_setup_platform platform = await integration.async_get_platform(domain) File "/usr/src/homeassistant/homeassistant/loader.py", line 1111, in async_get_platform platforms = await self.async_get_platforms((platform_name,)) File "/usr/src/homeassistant/homeassistant/loader.py", line 1176, in async_get_platforms platforms.update(self._load_platforms(platform_names)) File "/usr/src/homeassistant/homeassistant/loader.py", line 1101, in _load_platforms platform_name: self._load_platform(platform_name) File "/usr/src/homeassistant/homeassistant/loader.py", line 1275, in _load_platform cache[full_name] = self._import_platform(platform_name) File "/usr/src/homeassistant/homeassistant/loader.py", line 1307, in _import_platform return importlib.import_module(f"{self.pkg_path}.{platform_name}")

**Comment by DEDEit** [comment]
Hi!
Same problem, I solved it by modifying the vacuum.py in the custom folder. You just need to change a few lines:

FROM:

`from homeassistant.components.vacuum import (
    STATE_DOCKED,
    STATE_ERROR,
    STATE_IDLE,
    STATE_PAUSED,
    STATE_RETURNING,
    StateVacuumEntity,
    VacuumEntityFeature,
)
`

TO:

`from homeassistant.components.vacuum import StateVacuumEntity, VacuumEntityFeature
STATE_CLEANING = "cleaning"
STATE_DOCKED = "docked"
STATE_ERROR = "error"
STATE_IDLE = "idle"
STATE_PAUSED = "paused"
STATE_RETURNING = "returning"
`

This is basically to align with the new 2026.2.0.

Let me know :)

**Comment by carleoneman** [comment]
I change to this one, and restarted HA:

FROM:
from homeassistant.components.vacuum import ( STATE_DOCKED, STATE_ERROR, STATE_IDLE, STATE_PAUSED, STATE_RETURNING, StateVacuumEntity, VacuumEntityFeature, ) 


TO:
from homeassistant.components.vacuum import (
    StateVacuumEntity,
    VacuumEntityFeature,
)

STATE_CLEANING = "cleaning"
STATE_DOCKED = "docked"
STATE_ERROR = "error"
STATE_IDLE = "idle"
STATE_PAUSED = "paused"
STATE_RETURNING = "returning"


Then everything looks good :)

**Comment by Jezza34000** [comment]
Hi @DEDEit can you open a Pull request for the fix you mentioned above ? Thank you

**Comment by DEDEit** [comment]
> Hi [@DEDEit](https://github.com/DEDEit) can you open a Pull request for the fix you mentioned above ? Thank you

@Jezza34000  Hi, I'd love to do that, but it won't let me. When I click "new pull request," it asks me to compare two changes, but I can't find them.
