### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Metlock11** [Jezza34000/homeassistant_weback_component#45]
### Device brand

Zeegma

### Device model

next

### Smartphone application

HA 2026.2.1

### HA core version

2026.2.1

### Describe the problem

error in ha log

### Home Assistant Logs

nable to prepare setup for platform 'weback_vacuum.vacuum': Platform not found (cannot import name 'STATE_CLEANING' from 'homeassistant.components.vacuum' (/usr/src/homeassistant/homeassistant/components/vacuum/__init__.py)).

**Comment by Metlock11** [comment]
Detected that custom integration 'weback_vacuum' is setting the battery_level which has been deprecated. Integration weback_vacuum should implement a sensor instead with a correct device class and link it to the same device. This will stop working in Home Assistant 2026.8, please create a bug report at https://github.com/Jezza34000/homeassistant_weback_component/issues

**Comment by Jezza34000** [comment]
Hi,
As indicated on the project page, this integration is no longer maintained. 
The bug will not be fixed.
However, pull requests are still accepted.

**Comment by Crassus1988** [comment]
Hi anbei eine angepasste vacuum.py.

Homeassistant hat die Abfrage der States geändert
bei mir läuft es wieder.

Gruß Crassus

[vacuum.py](https://github.com/user-attachments/files/25443010/vacuum.py)

**Comment by Metlock11** [comment]
U mnie nie działa twój plik.
